//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 04:24:15 AM PDT 
//


package com.qualitylogic.openadr.core.signal;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Transport Interface delineates the edges at either end of a transport segment.
 * 
 * <p>Java class for TransportInterfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportInterfaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pointOfReceipt" type="{http://docs.oasis-open.org/ns/emix/2011/06/power}NodeType"/>
 *         &lt;element name="pointOfDelivery" type="{http://docs.oasis-open.org/ns/emix/2011/06/power}NodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportInterfaceType", namespace = "http://docs.oasis-open.org/ns/emix/2011/06/power", propOrder = {
    "pointOfReceipt",
    "pointOfDelivery"
})
public class TransportInterfaceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String pointOfReceipt;
    @XmlElement(required = true)
    protected String pointOfDelivery;

    /**
     * Gets the value of the pointOfReceipt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointOfReceipt() {
        return pointOfReceipt;
    }

    /**
     * Sets the value of the pointOfReceipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointOfReceipt(String value) {
        this.pointOfReceipt = value;
    }

    /**
     * Gets the value of the pointOfDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointOfDelivery() {
        return pointOfDelivery;
    }

    /**
     * Sets the value of the pointOfDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointOfDelivery(String value) {
        this.pointOfDelivery = value;
    }

}
