//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 04:24:15 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:icalendar-2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.qualitylogic.openadr.core.signal.xcal;
