//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.08 at 01:07:11 PM IST 
//


package com.honeywell.openadr.core.signal;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oadrService" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrServiceName"/>
 *                   &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrInfo" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oadrService"
})
@XmlRootElement(name = "oadrServiceSpecificInfo")
public class OadrServiceSpecificInfo
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<OadrServiceSpecificInfo.OadrService> oadrService;

    /**
     * Gets the value of the oadrService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oadrService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOadrService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OadrServiceSpecificInfo.OadrService }
     * 
     * 
     */
    public List<OadrServiceSpecificInfo.OadrService> getOadrService() {
        if (oadrService == null) {
            oadrService = new ArrayList<OadrServiceSpecificInfo.OadrService>();
        }
        return this.oadrService;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrServiceName"/>
     *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrInfo" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "oadrServiceName",
        "oadrInfo"
    })
    public static class OadrService
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected OadrServiceNameType oadrServiceName;
        @XmlElement(required = true)
        protected List<OadrInfo> oadrInfo;

        /**
         * Gets the value of the oadrServiceName property.
         * 
         * @return
         *     possible object is
         *     {@link OadrServiceNameType }
         *     
         */
        public OadrServiceNameType getOadrServiceName() {
            return oadrServiceName;
        }

        /**
         * Sets the value of the oadrServiceName property.
         * 
         * @param value
         *     allowed object is
         *     {@link OadrServiceNameType }
         *     
         */
        public void setOadrServiceName(OadrServiceNameType value) {
            this.oadrServiceName = value;
        }

        /**
         * Gets the value of the oadrInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the oadrInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOadrInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OadrInfo }
         * 
         * 
         */
        public List<OadrInfo> getOadrInfo() {
            if (oadrInfo == null) {
                oadrInfo = new ArrayList<OadrInfo>();
            }
            return this.oadrInfo;
        }

    }

}
