<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://services.ven.honeywell.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://services.ven.honeywell.com" xmlns:intf="http://services.ven.honeywell.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="VenSimService">

   </wsdl:portType>

   <wsdl:binding name="VenSimServiceSoapBinding" type="impl:VenSimService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="VenSimServiceService">

      <wsdl:port binding="impl:VenSimServiceSoapBinding" name="VenSimService">

         <wsdlsoap:address location="http://tempuri.org/GatewaySimulator/services/VenSimService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
